### ISSUE TITLE
onPageSelected called twice

### ISSUE THREAD

**Issue by milosnk** [kenilt/LoopingViewPager#3]
Hello there,

I've noticed a little issue, when going from last to first and vice versa from first to last page, onPageSelected() method is called twice.

Is there chance to fix this?

Thanks

**Comment by kenilt** [comment]
Ah, thanks for your report. I've got it. Finding a way to solve this issue.

**Comment by ra1vo** [comment]
When swiping from last to first item, first fragment is calling onAttach(), onCreateView() again once it is selected. Once when pager is in previous position and again when item is selected.

**Comment by milosnk** [comment]
It's working well now, thanks 👍
