### ISSUE TITLE
Auto scrolling while touching the view pager

### ISSUE THREAD

**Issue by skydev66** [kenilt/LoopingViewPager#8]
When I touch the screen and drag, the view pager automatically goes to next page by Auto scroller. Maybe auto scroll should be disabled while touching, and enabled again after touching finished.

**Comment by soochun-deali** [comment]
Hello. I had the same problem. I solved it by myself. Hope it's helpful.

    class AutoScrollerval viewPager: ViewPager, lifecy .... : LifecycleObserver, ScrollerObserver {
        private val stopScrollWhenTouch = true
        private var isStopByTouch = false
                        :
                        :

        init {
          viewPager.setOnTouchListener { v, event ->
              if (stopScrollWhenTouch) {
                  if (event.action == MotionEvent.ACTION_DOWN) {
                      isStopByTouch = true
                      removeAutoScrollCallback()
                  } else if (event.action == MotionEvent.ACTION_UP && isStopByTouch) {
                      isStopByTouch = false
                      resumeAutoScrollWhenNeeded()
                  }
              }
  
              return@setOnTouchListener false
          }
                        :
                        :

      }

**Comment by soochun-deali** [comment]
The second way. I think it's better. 

    class LoopingViewPager : ViewPager {
        var autoScroller: AutoScroller? = null
        private val stopScrollWhenTouch = true
        private var isStopByTouch = false
        
        override fun dispatchTouchEvent(event: MotionEvent?): Boolean {
              if (stopScrollWhenTouch) {
                  if (event?.action == MotionEvent.ACTION_DOWN) {
                      isStopByTouch = true
                      autoScroller?.removeAutoScrollCallback()
                  } else if (event?.action == MotionEvent.ACTION_UP && isStopByTouch) {
                      isStopByTouch = false
                      autoScroller?.resumeAutoScrollWhenNeeded()
                  }
              }
              return super.dispatchTouchEvent(event)
          }

         fun setAutoScroller(lifecycle: Lifecycle? = null, autoScrollInterval: Long) {
              autoScroller = AutoScroller(this, lifecycle, autoScrollInterval)
          }

**Comment by skydev66** [comment]
Good solutions. Thank you.

**Comment by kenilt** [comment]
@soochun-deali thanks for your idea, I've applied your idea in this pull request #9. I just have 1 concern that the auto scroller will be restart 2 times after every drag finished. Still consider it.
